#!/usr/bin/env sh
# This file is part of r-parser. It is subject to the license terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/r-parser/master/COPYRIGHT. No part of r-parser, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
# Copyright © 2021 The developers of r-parser. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/r-parser/master/COPYRIGHT.


set -e
set -u
set -f


main()
{
	local build_profile_sh_file_path="$1"
	local action="$2"
	local target="$3"
	local cpu_profile="$4"
	local cargo_binary_path="$5"
	local build_profile_toml_file_path="$6"
	shift 6

	. "$build_profile_sh_file_path" "$action" "$target" "$cpu_profile"
	exec "$cargo_binary_path" -Zunstable-options -Zconfig-include --config "$build_profile_toml_file_path" "$@"
}

main "$@"
